#!/system/bin/sh
# Script to launch frandom at boot by Ryuinferno @ XDA

if [ /proc/config.gz ]; then
insmod /system/lib/modules/frandom-2ndboot.ko
chmod 644 /dev/frandom
mv /dev/random /dev/random.ori
mv /dev/urandom /dev/urandom.ori
ln /dev/frandom /dev/random
chmod 644 /dev/random
ln /dev/frandom /dev/urandom
chmod 644 /dev/urandom
